/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pharmicie;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;









/**
 *
 * @author Eng-BASIL BARAKAT
 */
public class PharmiacyForm extends javax.swing.JFrame  {
    
  public  File f=new File("Medicine.txt");
  public  Medicine  m=new Medicine();
  
 // public  Vector<Medicine> vector=new Vector<>();
  public  ArrayList<Medicine> ml=new ArrayList<Medicine>();
    

    /**
     * Creates new form PharmiacyForm
     */
    public PharmiacyForm() {
        ml= m.resdfile(f);
       System.out.print(ml.get(1));
       // File f=new File("Medicine.txt");
        if(f.exists())System.out.print("Good");
        //rede   
      //  Scanner s=new Scanner(f);
    
{
         
        }
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MedicineName = new javax.swing.JTextField();
        geanricName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Dosage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        exirationDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        drugCode = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        search = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel7.setBackground(new java.awt.Color(153, 204, 0));
        jLabel7.setAutoscrolls(true);
        jLabel7.setMaximumSize(new java.awt.Dimension(512, 512));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Msys\\OneDrive\\Documents\\NetBeansProjects\\Pharmicie\\src\\main\\java\\Images\\Medicine imege.png")); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setBackground(new java.awt.Color(102, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Medicine brand name");

        MedicineName.setBackground(new java.awt.Color(204, 255, 255));
        MedicineName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MedicineName.setForeground(new java.awt.Color(0, 102, 102));
        MedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineNameActionPerformed(evt);
            }
        });

        geanricName.setBackground(new java.awt.Color(204, 255, 255));
        geanricName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        geanricName.setForeground(new java.awt.Color(0, 102, 102));
        geanricName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geanricNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Medicine geanric name");

        Dosage.setBackground(new java.awt.Color(204, 255, 255));
        Dosage.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Dosage.setForeground(new java.awt.Color(0, 102, 102));
        Dosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosageActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Dosage(strength of medication)");

        exirationDate.setBackground(new java.awt.Color(204, 255, 255));
        exirationDate.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        exirationDate.setForeground(new java.awt.Color(0, 102, 102));
        exirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exirationDateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Expiration date");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("National Drug code");

        drugCode.setBackground(new java.awt.Color(204, 255, 255));
        drugCode.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        drugCode.setForeground(new java.awt.Color(0, 102, 102));
        drugCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCodeActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(51, 255, 204));
        delete.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        delete.setText("Delete");
        delete.setAutoscrolls(true);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(51, 255, 204));
        update.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(51, 255, 204));
        search.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(51, 255, 204));
        save.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText(" Welcome to the information page");

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(save)
                                .addGap(43, 43, 43)
                                .addComponent(search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(geanricName, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(MedicineName))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exirationDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dosage)
                                    .addComponent(drugCode))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(update)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(158, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geanricName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Dosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(drugCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==save){
        m.medicineName=MedicineName.getText();
        m.geanricName=geanricName.getText();
        m.dsage=Dosage.getText();
        m.exirationDate=exirationDate.getText();
        m.drugCode=drugCode.getText();
     
       // vector.addElement(m);
        
       ml.add(m);
     
      //   File f=new File("Medicine.txt");
        try {
            BufferedWriter writer=new BufferedWriter(new FileWriter("Medicine.txt")); 
          //  PrintWriter pw=new PrintWriter(f);
       for(int i=0;i<ml.size();i++ ){ 
           Medicine e=ml.get(i);
           writer.write(e.medicineName+"\t"+e.geanricName+"\t"+e.dsage+"\t"+e.exirationDate+"\t"+e.drugCode+"\n");}
           
            writer.close();
            
        } catch (FileNotFoundException e) {
            System.out.print("The file dosent exsit");
        } catch (IOException ex) {
        Logger.getLogger(PharmiacyForm.class.getName()).log(Level.SEVERE, null, ex);
    }
	 JOptionPane.showMessageDialog(null, "Save The Change  Successfully ");
         MedicineName.setText("");
         geanricName.setText("");
         Dosage.setText("");
         exirationDate.setText("");
         drugCode.setText("");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
       // if(Dosage.getText()=="") JOptionPane.showMessageDialog(null, "The dosege Tixt Filed is Emptye ");
      // File f=new File("Medicine.txt");
      if(evt.getSource()==search){
      if(Dosage.getText().equals("")&&MedicineName.getText().equals("")&&geanricName.getText().equals("")&&exirationDate.getText().equals("")&&drugCode.getText().equals(""))JOptionPane.showMessageDialog(null, "The Tixet Felids is Empty!");
        
      
      
        boolean found=false;
     
               String mn=MedicineName.getText();
               String gn=geanricName.getText();
               String d=Dosage.getText();
               String ex=exirationDate.getText();
               String dc=drugCode.getText();
              
               for(int i=0; i<ml.size();i++){
                   Medicine typ=new Medicine();
                   typ=ml.get(i);
                   if(mn.equals(typ.medicineName)||gn.equals(typ.geanricName)||d.equals(typ.dsage)||ex.equals(typ.exirationDate)||dc.equals(typ.drugCode)){
                       MedicineName.setText(typ.medicineName);
                       geanricName.setText(typ.geanricName);
                       Dosage.setText(typ.dsage);
                       exirationDate.setText(typ.exirationDate); 
                       drugCode.setText(typ.drugCode);
                       found=true;
                   }
               }
      }
        
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==update){
          
            String mn=MedicineName.getText();
               String gn=geanricName.getText();
               String d=Dosage.getText();
               String ex=exirationDate.getText();
               String dc=drugCode.getText();
              
               for(int i=0; i<ml.size();i++){
                      Medicine typ=new Medicine();
                   typ=ml.get(i); 
   if(mn.equals(typ.medicineName)||gn.equals(typ.geanricName)||d.equals(typ.dsage)||ex.equals(typ.exirationDate)||dc.equals(typ.drugCode)){

        ml.get(i).medicineName=mn;
        ml.get(i).geanricName=gn;
        ml.get(i).dsage=d;
        ml.get(i).exirationDate=ex;
        ml.get(i).drugCode=dc;
        System.out.print(ml.get(i));
         JOptionPane.showMessageDialog(null, "The Update Process Was Completed !");
   }
               }
              
               
              m.writeFile(ml);
                      m.copyFile();

        }    
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        if(evt.getSource()==delete){
              
            String mn=MedicineName.getText();
               String gn=geanricName.getText();
               String d=Dosage.getText();
               String ex=exirationDate.getText();
               String dc=drugCode.getText();
              
               for(int i=0; i<ml.size();i++){
                     Medicine typ=new Medicine();
                   typ=ml.get(i); 
    if(mn.equals(typ.medicineName)||gn.equals(typ.geanricName)||d.equals(typ.dsage)||ex.equals(typ.exirationDate)||dc.equals(typ.drugCode)){
        
        
        ml.remove(i);
       JOptionPane.showMessageDialog(null, "The deletoin Was Completed !");
                 }
        }
          m.writeFile(ml);
                  m.copyFile();

    }//GEN-LAST:event_deleteActionPerformed
    }
    private void drugCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugCodeActionPerformed

    private void exirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exirationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exirationDateActionPerformed

    private void DosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DosageActionPerformed

    private void geanricNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geanricNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geanricNameActionPerformed

    private void MedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MedicineName.setText("");
         geanricName.setText("");
         Dosage.setText("");
         exirationDate.setText("");
         drugCode.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmiacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmiacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmiacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmiacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PharmiacyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dosage;
    private javax.swing.JTextField MedicineName;
    private javax.swing.JButton delete;
    private javax.swing.JTextField drugCode;
    private javax.swing.JTextField exirationDate;
    private javax.swing.JTextField geanricName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
